### ISSUE TITLE
Option "--collaborate" opens repository and executes default command

### ISSUE THREAD

**Issue by RaulCatalinas** [RaulCatalinas/HuskyBC#3]
The ``--collaborate`` option is currently causing unintended behavior when executed. 

Instead of simply opening the associated GitHub repository in the user's default web browser, it also executes the default command of the CLI.

**Comment by xxxAlvaDevxxx** [comment]
The problem is caused by the fact that program.args is for the entry of each option.

example:

bun run split.js -s / --first a/b/c
[ 'a' ]

![Image](https://github.com/RaulCatalinas/HuskyBC/assets/106893746/6ade3e6c-a634-4ac3-8ef9-a60501161eb7)

source: https://www.npmjs.com/package/commander

**Comment by RaulCatalinas** [comment]
Ok
